"""empty message

Revision ID: 063cfb907a5c
Revises: 
Create Date: 2021-08-18 20:55:32.437776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063cfb907a5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('menu',
    sa.Column('menu_no', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.String(length=200), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('menu_kate', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('menu_no')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('menu')
    op.drop_table('member')
    # ### end Alembic commands ###
