"""empty message

Revision ID: 0eb0224c9f73
Revises: d28581840a7a
Create Date: 2021-08-24 12:24:12.849069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb0224c9f73'
down_revision = 'd28581840a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer_question_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_question_id_question'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer_question_id_question', 'question', ['question_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
