"""empty message

Revision ID: 2c254bccd26e
Revises: e3abf9e5bb79
Create Date: 2021-08-22 12:31:20.819432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c254bccd26e'
down_revision = 'e3abf9e5bb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('id', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_column('member', 'id')
    # ### end Alembic commands ###
