"""empty message

Revision ID: 318e19b5a456
Revises: e33137d27237
Create Date: 2021-09-01 09:41:45.215634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318e19b5a456'
down_revision = 'e33137d27237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('adminId', name=op.f('pk_admin'))
    )
    op.create_table('categories',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('categoryId', name=op.f('pk_categories'))
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_users'))
    )
    op.create_table('products',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], name=op.f('fk_products_categoryId_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productId', name=op.f('pk_products'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], name=op.f('fk_question_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], name=op.f('fk_answer_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    op.create_table('cart',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['products.productId'], name=op.f('fk_cart_productId_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_cart_userId_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'productId', name=op.f('pk_cart'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('admin')
    # ### end Alembic commands ###
