"""empty message

Revision ID: 3536cefdcd42
Revises: f505ccf4faba
Create Date: 2021-09-09 14:40:16.240490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3536cefdcd42'
down_revision = 'f505ccf4faba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cart',
    sa.Column('cartId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['image'], ['products.image'], name=op.f('fk_Cart_image_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name'], ['products.name'], name=op.f('fk_Cart_name_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price'], ['products.price'], name=op.f('fk_Cart_price_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['products.productId'], name=op.f('fk_Cart_productId_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_Cart_userId_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cartId', 'productId', name=op.f('pk_Cart')),
    sqlite_autoincrement=True
    )
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.Column('qty', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('productId', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['image'], ['products.image'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name'], ['products.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price'], ['products.price'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['products.productId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE')
    )
    op.drop_table('Cart')
    # ### end Alembic commands ###
