"""empty message

Revision ID: 4d6e1574006a
Revises: 9fe967104b13
Create Date: 2021-08-24 15:04:22.232332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6e1574006a'
down_revision = '9fe967104b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('fk_answer_user_no_member', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_user_id_member'), 'member', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_no')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('fk_question_user_no_member', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_member'), 'member', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_no', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_member'), type_='foreignkey')
        batch_op.create_foreign_key('fk_question_user_no_member', 'member', ['user_no'], ['no'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_no', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_answer_user_id_member'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer_user_no_member', 'member', ['user_no'], ['no'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
