"""empty message

Revision ID: 623a1e6fbad6
Revises: bb683bd73b1b
Create Date: 2021-08-22 13:09:59.678073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623a1e6fbad6'
down_revision = 'bb683bd73b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('ad_no', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(length=200), nullable=False),
    sa.Column('ad_name', sa.String(length=200), nullable=False),
    sa.Column('ad_email', sa.String(length=200), nullable=False),
    sa.Column('ad_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ad_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
