"""empty message

Revision ID: 640419055f5f
Revises: 65f967e3fe4e
Create Date: 2021-08-23 15:08:59.765427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640419055f5f'
down_revision = '65f967e3fe4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
