"""empty message

Revision ID: 72680e0a4ff5
Revises: c09e9573901f
Create Date: 2021-09-10 11:46:12.164397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72680e0a4ff5'
down_revision = 'c09e9573901f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.drop_constraint('uq_Cart_cartId', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_Cart_cartId', ['cartId'])

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
