"""empty message

Revision ID: 7cd131fcbb60
Revises: b0d5f851fb6d
Create Date: 2021-09-10 11:54:10.182033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd131fcbb60'
down_revision = 'b0d5f851fb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cart_cartId', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cart_cartId', ['cartId'])

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
