"""empty message

Revision ID: 807ee0e4e022
Revises: 063cfb907a5c
Create Date: 2021-08-18 20:59:24.854885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807ee0e4e022'
down_revision = '063cfb907a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
