"""empty message

Revision ID: 854c07ee4dab
Revises: b298dc0cbca7
Create Date: 2021-09-10 12:20:09.701103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854c07ee4dab'
down_revision = 'b298dc0cbca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
