"""empty message

Revision ID: 9fe6370b0c3b
Revises: 623a1e6fbad6
Create Date: 2021-08-23 14:52:06.508042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe6370b0c3b'
down_revision = '623a1e6fbad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_member_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_member_email'), type_='unique')

    # ### end Alembic commands ###
