"""empty message

Revision ID: 9fe967104b13
Revises: 0057886dfda1
Create Date: 2021-08-24 12:41:00.402993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe967104b13'
down_revision = '0057886dfda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_no',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_no',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_no',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_no',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
