"""empty message

Revision ID: af26b0b9ee4e
Revises: f574da194e42
Create Date: 2021-08-24 12:19:18.298711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af26b0b9ee4e'
down_revision = 'f574da194e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('ad_no', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(length=200), nullable=False),
    sa.Column('ad_name', sa.String(length=200), nullable=False),
    sa.Column('ad_email', sa.String(length=200), nullable=False),
    sa.Column('ad_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ad_no', name=op.f('pk_admin'))
    )
    op.create_table('member',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_member')),
    sa.UniqueConstraint('email', name=op.f('uq_member_email'))
    )
    op.create_table('menu',
    sa.Column('menu_no', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.String(length=200), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('menu_kate', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('menu_no', name=op.f('pk_menu'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], name=op.f('fk_question_user_id_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], name=op.f('fk_answer_user_id_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('menu')
    op.drop_table('member')
    op.drop_table('admin')
    # ### end Alembic commands ###
