"""empty message

Revision ID: c4b0d8f696ad
Revises: 3728ec429df9
Create Date: 2021-09-07 15:16:19.513085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b0d8f696ad'
down_revision = '3728ec429df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'products', ['price'], ['price'], ondelete='CASCADE')

    # ### end Alembic commands ###
