"""empty message

Revision ID: d3ec33509303
Revises: 0ed5816d3fbd
Create Date: 2021-08-22 12:52:31.118371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ec33509303'
down_revision = '0ed5816d3fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('id', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_column('member', 'id')
    # ### end Alembic commands ###
