"""empty message

Revision ID: e3abf9e5bb79
Revises: cf676d235bcd
Create Date: 2021-08-22 12:29:18.451710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3abf9e5bb79'
down_revision = 'cf676d235bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('id', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_column('member', 'id')
    # ### end Alembic commands ###
