"""empty message

Revision ID: f505ccf4faba
Revises: 78e39af4965d
Create Date: 2021-09-07 16:37:56.003273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f505ccf4faba'
down_revision = '78e39af4965d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=True))
        batch_op.drop_column('Qty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Qty', sa.INTEGER(), nullable=True))
        batch_op.drop_column('qty')

    # ### end Alembic commands ###
